apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_service
        imagePullPolicy: Never
        ports:
        - name: ftps
          containerPort: 21
        - name: min
          containerPort: 21010
        - name: max
          containerPort: 21011
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /tmp/health.sh
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
  - name : ftps
    port: 21
    targetPort: 21
  - name: min
    port: 21010
    targetPort: 21010
  - name: max
    port: 21011
    targetPort: 21011
  type: LoadBalancer
