apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_service
        resources:
          limits:
            memory: "128Mi"
            cpu: "700m"
        ports:
        - containerPort: 21
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
  type: LoadBalancer
