apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - name : mysql
    protocol : TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
  clusterIP: 10.101.88.129
  

# Will open access to an application within a cluster, without access from the world.
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_service
        imagePullPolicy: Never
        ports:
        - name : sql
          containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql 
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    name : mysql
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
