apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22

---
apiVersion: apps/v1  # version 
kind: Deployment 
# metadata part 
metadata:   # Metadata is data that describes other data
  name: nginx # the key-value pair  of the depl
  labels:
    app: nginx
# specification part 
spec:
  replicas: 1
  selector: # makes a cnx btw the service and its pod
    matchLabels:
      app: nginx
# this configuraton  applies to a pod / container
  template:
  # pod metadata
    metadata:
      labels:
        app: nginx
  # pod spec 
    spec:
      containers:
      - name: nginx
        image: nginx_service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name : http
          containerPort: 80
        - name : https
          containerPort: 443
        - name : ssh
          containerPort: 22
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
